### ISSUE TITLE
CA Certificates Is Empty

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.freedesktop.Sdk.Extension.openjdk9#2]
We're not shipping CA Certs properly for the Java trust root which is [breaking Minecraft](https://github.com/flathub/flathub/pull/160).

> It looks like that the OpenJDK trust store is missing or empty.
I have tried adding -Djavax.net.ssl.trustStore=/app/jre/jvm/openjdk-9/lib/security/cacerts to the Minecraft launch command, but unfortunately, no luck.
I believe Debian has ca-certificates-java package for this, so maybe we could use it.

**Comment by mbooth101** [comment]
In Fedora, the ca-certificates package does this at build time:

    p11-kit extract --format=java-cacerts --filter=ca-anchors --overwrite --purpose server-auth /etc/pki/ca-trust/extracted/java/cacerts

I.e.: http://pkgs.fedoraproject.org/cgit/rpms/ca-certificates.git/tree/update-ca-trust#n21

And then the JRE package just symlinks that cacerts file to /usr/lib/jvm/java-openjdk/jre/lib/security/cacerts

I am able to work around this symlinking to the host version of cacerts into my JRE:

    cp -ar /usr/lib/sdk/openjdk9/jvm/openjdk-9 /app/java
    ln -sf /var/run/host/etc/pki/ca-trust/extracted/java/cacerts /app/java/lib/security/cacerts

But this is less than ideal, and really should be fixed in the freedesktop.org runtime, where ca-certificates lives.

FWIW, this is the same problem as https://bugzilla.redhat.com/show_bug.cgi?id=1513989

**Comment by nedrichards** [comment]
So there's a --with-cacerts configure option in the JDK that you can use to point to a valid certificate store which we could either ship in the package or have in the base runtime, or, as you say, link to one in the system.

JDK10 - which should be GA in March 2018 will [ship with certificates by default](http://openjdk.java.net/projects/jdk/10/).

**Comment by AsciiWolf** [comment]
Any news?

**Comment by Alexander-Wilms** [comment]
JDK 10 has been released: http://jdk.java.net/10/

**Comment by AsciiWolf** [comment]
@Alexander-Wilms Cool! I hope this will finally fix the empty CA certificates issue.

**Comment by AsciiWolf** [comment]
OpenJDK 10 is now on Flathub.

**Comment by mbooth101** [comment]
The latest builds of both the OpenJDK 9 and 10 extensions should both now have a filled cacerts file. I'm going to close this ticket now, but please shout up if there are still problems.

**Comment by AsciiWolf** [comment]
It looks like that this is still an issue; see [this comment](https://github.com/flathub/flathub/pull/160#issuecomment-406454242).

**Comment by nedrichards** [comment]
Not true, the new minecraft uses a built-in JRE rather than openjdk.

**Comment by nedrichards** [comment]
I'm sorry, I've read this more closely and saw that you added a new JRE back again. Makes sense, however I see that's openjdk10 rather than 9, best to open a new issue about it there.
